version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/cnot_connect
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: cnot123
    # The command to run the app using dockerize
    entrypoint: ["dockerize", "-wait", "tcp://db:3306", "-timeout", "60s", "java", "-jar", "target/CnotConnect-1-0.0.1-SNAPSHOT.jar"]

  db:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: cnot123
      MYSQL_DATABASE: cnot_connect
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
